---

# man:glab-config(1)


# Open Neovim as editor for issues and merge requests, among other things.
editor: nvim

git_protocol: ssh

# configuration settings for GitLab instances
hosts:

    gitlab.archlinux.org:
        api_protocol: https
        user: djsp

    gitlab.com:
        api_protocol: https
        user: djsp

    gitlab.freedesktop.org:
        api_protocol: https
        user: djsp

    gitlab.gnome.org:
        api_protocol: https
        user: djsp

# default GitLab instance
host: gitlab.com
