# configuration for GitLab CLI (glab)
# man:glab-config(1)

# SPDX-FileCopyrightText: © 2025 David Joaquín Shourabi Porcel <https://www.djsp.eu/>
# SPDX-License-Identifier: AGPL-3.0-only


---

editor: nvim

git_protocol: ssh

# configuration settings for GitLab instances
hosts:

    gitlab.com:
        api_protocol: https
        user: djsp

# default GitLab instance
host: gitlab.com
