# This file is sourced by `/etc/profile.d/locale.sh` instead of `/etc/locale.conf` on Arch Linux.
# Other distributions ignore it.

# The format of this file is explained in the man page locale.conf(5).
# Because applications other than the shell may read this file,
# shell features beyond mere variable assignments should be avoided.

# The settings in this file are described in the man page locale(7).

LANG=en_US.UTF-8

# German addressing has the Postleitzahl precede the city name
LC_ADDRESS=de_DE.UTF-8

# With the usual value for `LC_COLLATE`, `C`, sorting is case sensitive: `B` comes before `a`.
# With `en_US.UTF-8`, sorting is not case sensitive: `a` comes before `B`.
# However, initial dots are ignored when sorting; dotfiles are sorted as if they didn't have a dot at the start.
LC_COLLATE=en_US.UTF-8

# metric system/units
LC_MEASUREMENT=en_DK.UTF-8

# formatting used for monetary-related numeric values,
# including the [radix point](https://en.wikipedia.org/wiki/Radix_point)
#
# foobar:
#
# locale	`currency_symbol`
# de_DE.UTF-8	€
# en_DK.UTF-8	kr.
# en_GB.UTF-8	£
# en_US.UTF-8	$
#
# may be checked with the command: `LC_MONETARY=... locale -- currency_symbol`
LC_MONETARY=de_DE.UTF-8

# period as thousands separator
# comma as decimal separator / radix
LC_NUMERIC=en_DK.UTF-8

LC_PAPER=de_DE.UTF-8

LC_TELEPHONE=de_DE.UTF-8

# ISO 8601
# https://serverfault.com/a/17184/479564
# https://unix.stackexchange.com/a/272665/54084
LC_TIME=en_DK.UTF-8
