# configuration for GitHub CLI (gh)
# https://cli.github.com/manual/gh_config

# SPDX-FileCopyrightText: © 2025 David Joaquín Shourabi Porcel <https://www.djsp.eu/>
# SPDX-License-Identifier: AGPL-3.0-only


---

editor: nvim

version: '1'
