# pip user configuration file
# https://pip.pypa.io/en/stable/topics/configuration/

# SPDX-FileCopyrightText: © 2025 David Joaquín Shourabi Porcel <https://www.djsp.eu/>
# SPDX-License-Identifier: AGPL-3.0-only


[global]

# Prevent pip from installing Python packages outside of virtual environments
require-virtualenv = yes
