# configuration for Poetry, a Python project manager
# https://python-poetry.org/docs/configuration/

# SPDX-FileCopyrightText: © 2025 David Joaquín Shourabi Porcel <https://www.djsp.eu/>
# SPDX-License-Identifier: AGPL-3.0-only
